apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  selector:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
