apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080