service:
  name: gateway

resources:
  limits:
    cpu: "0.1"
    memory: "128Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

env:
  - name: DB_USERNAME
    value: root
  - name: DB_PASSWORD
    value: YUfdayzwlx
  - name: DB_HOST
    value: "mongodb.default.svc.cluster.local"
  - name: PORT
    value: "8080"
  - name: version
    value: "1.0.2"