service:
  name: dbproxy
  version: "1.0.0"

resources:
  limits:
    cpu: "0.1"
    memory: "128Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

env:
  - name: RABBITMQ_URL
    value: "rabbitmq.default.svc.cluster.local"
  - name: RABBITMQ_USER
    value: user
  - name: RABBITMQ_PASS
    value: BLzIj3qDTj
  - name: DB_USERNAME
    value: root
  - name: DB_PASSWORD
    value: YUfdayzwlx
  - name: DB_HOST
    value: "mongodb.default.svc.cluster.local"
  - name: version
    value: "1.0.3"