apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - env:
{{ toYaml .Values.env | indent 8 }}
        image: "public.ecr.aws/y8l5h6t0/helphack/{{ .Chart.Name }}:latest"
        name: "{{ .Chart.Name }}"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Always
